import { randomBytes } from 'node:crypto';
export const stations = { control:{x:-12,z:3}, observation:{x:13,z:-9} };
export const evidence = {log:{x:-10,z:1},plate:{x:-12,z:3},diagram:{x:8,z:-7},response:{x:13,z:-9},secret:{x:22,z:12}};
const modes=['steady','alternating','staged'];
export class RoomStore {
 constructor(now=()=>Date.now()){this.now=now;this.rooms=new Map();}
 cleanup(){for(const [code,r]of this.rooms)if(r.expires<this.now())this.rooms.delete(code);}

 create(name){this.cleanup();if(this.rooms.size>=25)throw Error('Room capacity reached. Try again shortly.');let code;do{code=Array.from(randomBytes(6),v=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[v%32]).join('');}while(this.rooms.has(code));const r={code,run:randomBytes(8).toString('hex'),variant:modes[randomBytes(1)[0]%3],mode:'steady',isolated:false,phase:'waiting',players:[],discoveries:{},revision:0,control:null,test:null,confirmation:null,activationAt:null,created:this.now(),expires:this.now()+4*3600e3,votes:[],log:[]};r.mode=modes[(modes.indexOf(r.variant)+1)%3];this.rooms.set(code,r);return this.join(code,name);}
 join(code,name,token){const r=this.rooms.get(code?.toUpperCase());if(!r||r.expires<this.now()){const error=new Error('This room has ended or expired. Create a new room.');error.code='ROOM_GONE';throw error;}let p=token?r.players.find(p=>p.token===token&&!p.removed):null;if(token&&!p){const error=new Error('Your reconnect identity is no longer available. Join again with the room code.');error.code='IDENTITY_GONE';throw error;}if(!p){const held=r.players.filter(p=>!p.removed&&(p.connected||this.now()-(p.leftAt||0)<120e3));if(held.length>=4)throw Error('Room is full.');p={id:randomBytes(8).toString('hex'),token:randomBytes(24).toString('hex'),name:String(name||'Visitor').replace(/[<>]/g,'').trim().slice(0,24)||'Visitor',x:0,z:18,yaw:0,connected:true,ready:false,leftAt:null};r.players.push(p);}else{if(r.players.filter(q=>q.connected&&q.id!==p.id).length>=4)throw Error('Room is full.');p.connected=true;p.leftAt=null;}r.expires=r.created+4*3600e3;r.votes=[];r.coordinator ||= p.id;return {r,p};}
 leave(r,p){p.connected=false;p.leftAt=this.now();r.votes=[];if(r.control===p.id){r.control=null;r.test=null;}if(r.coordinator===p.id)r.coordinator=r.players.find(q=>q.connected)?.id||null;if(!r.players.some(q=>q.connected))r.expires=Math.min(r.created+4*3600e3,this.now()+900e3);}
 snapshot(r){const test=r.test&&r.test.until>this.now()?{active:true,stable:r.test.stable}:null;let phase=r.phase;if(phase==='activating'&&this.now()-r.activationAt>=18000)phase=r.phase='restored';return {code:r.code,run:r.run,mode:r.mode,isolated:r.isolated,phase,revision:r.revision,discoveries:r.discoveries,players:r.players.filter(p=>!p.removed).map(({token,...p})=>p),control:r.control,test,confirmation:!!r.confirmation,activationAt:r.activationAt,coordinator:r.coordinator,votes:r.votes,log:r.log,serverTime:this.now(),expires:r.expires};}
 near(p,pos){return Math.hypot(p.x-pos.x,p.z-pos.z)<4;}
 act(r,p,a){if(r.expires<this.now())throw Error('Room expired. Create a new room.');if(!p.connected)throw Error('Reconnect to continue.');if(a.run!==r.run)throw Error('This action belongs to a previous run.');const connected=()=>r.players.filter(p=>p.connected);const say=t=>{r.log.push({name:p.name,text:t,at:this.now()});r.log=r.log.slice(-16);};
 if(a.type==='ready'){p.ready=true;if(connected().length>=2&&connected().every(q=>q.ready)&&r.phase==='waiting')r.phase='investigating';}
 else if(a.type==='ping'){const allowed=['Inspect this','Compare this','Ready','Stable','Try again'];if(!allowed.includes(a.text))throw Error('Unknown message.');say(a.text+' at '+Math.round(p.x)+', '+Math.round(p.z));}
 else if(a.type==='observation'){if(!this.near(p,stations.observation)||!r.test||r.test.until<this.now())throw Error('Observe at the regulator during a diagnostic.');say(this.response(r).label);}
 else if(a.type==='discover'){const point=evidence[a.id];if(!point||!this.near(p,point))throw Error('Move closer to inspect.');if(a.id==='secret'&&!(r.test&&r.test.until>this.now())&&!r.activationAt)throw Error('The sketch shows a seam. Observe it during a test.');if(!r.discoveries[a.id])r.discoveries[a.id]={by:p.name,at:this.now()};say('Shared '+a.id+' observation.');}
 else if(a.type==='replay'){if(r.phase!=='restored')throw Error('Restore the service first.');if(!r.votes.includes(p.id))r.votes.push(p.id);if(connected().every(q=>r.votes.includes(q.id))){const prev=r.variant;r.variant=modes[(modes.indexOf(prev)+1)%3];r.run=randomBytes(8).toString('hex');r.mode=modes[(modes.indexOf(r.variant)+1)%3];r.isolated=false;r.phase='investigating';r.discoveries={};r.test=null;r.control=null;r.confirmation=null;r.activationAt=null;r.votes=[];r.log=[];for(const q of r.players){q.x=0;q.z=18;q.ready=true;}}}
 else {if(r.phase==='waiting')throw Error('Two players must be ready to begin.');if(['activating','restored'].includes(r.phase))throw Error('Service is already restored.');if(a.revision!==r.revision)throw Error('Machine state changed; try again.');if(['isolate','mode','test','activate'].includes(a.type)&&!this.near(p,stations.control))throw Error('Operate this at the human interface.');
 if(a.type==='isolate'){r.isolated=true;r.confirmation=null;r.test=null;}
 else if(a.type==='mode'){if(!r.isolated)throw Error('Isolate the feed before changing configuration.');if(!modes.includes(a.mode))throw Error('Unknown coupling.');r.mode=a.mode;r.confirmation=null;r.test=null;}
 else if(a.type==='test'){if(!r.isolated)throw Error('Isolate the feed first.');r.control=p.id;r.test={until:this.now()+120e3,stable:r.mode===r.variant};r.confirmation=null;}
 else if(a.type==='confirm'){if(!this.near(p,stations.observation))throw Error('Observe at the ancient regulator.');if(!r.test||r.test.until<this.now())throw Error('Ask someone to run a diagnostic test.');if(r.control===p.id)throw Error('A different player must observe the regulator.');if(!r.players.find(q=>q.id===r.control&&q.connected))throw Error('The operator disconnected.');if(!r.test.stable)throw Error('Response is interrupted. Compare the diagram and try another setting.');r.confirmation={observer:p.id,controller:r.control,mode:r.mode};say('Confirmed stable response.');}
 else if(a.type==='activate'){const c=r.confirmation;if(!c||c.mode!==r.mode||!r.players.find(q=>q.id===c.observer&&q.connected)||!r.players.find(q=>q.id===c.controller&&q.connected))throw Error('Two connected players must establish stable confirmation.');r.activationAt=this.now();r.phase='activating';r.test=null;r.isolated=false;say('Restored the landing service.');}
 else throw Error('Unknown action.');r.revision++;}
 return this.snapshot(r);}
 response(r){return {pattern:r.variant,label:{steady:'Continuous stable extension',alternating:'Balanced back-and-forth motion',staged:'Three successive sections settle'}[r.variant]};}
}
