import * as THREE from 'three';import './style.css';
type State={code:string;run:string;mode:string;isolated:boolean;phase:string;revision:number;discoveries:Record<string,{by:string}>;players:any[];control:string|null;test:{active:boolean;stable:boolean}|null;confirmation:boolean;activationAt:number|null;coordinator:string;votes:string[];log:any[];serverTime:number};
const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<canvas id="world" aria-label="Riverside frontier landscape"></canvas><div id="veil"></div><main id="title"><div class="eyebrow">A COOPERATIVE FRONTIER MYSTERY</div><h1>WORLDS<br><span>AWAKENED</span></h1><p class="intro">A quiet landing. An ancient structure.<br>A connection waiting to be understood.</p><p class="description">Explore a beautiful human frontier, share what you discover, and work together to restore a connection humanity only partly understands.</p><p id="session-message" role="alert"></p><div class="form"><label>Your name<input id="name" maxlength="24" value="Visitor" autocomplete="nickname"></label><button id="resume" hidden>RETRY PREVIOUS ROOM</button><button id="create">CREATE ROOM <span>↗</span></button><div class="joinrow"><label class="sr" for="code">Room code</label><input id="code" maxlength="6" placeholder="ROOM CODE" autocomplete="off"><button id="join">JOIN ROOM</button></div></div><small>2–4 players · No account · No installation</small><button id="settings-open" class="quiet">Settings & accessibility</button></main><div id="loading" hidden><div class="eyebrow">WORLDS AWAKENED</div><h2>Arriving at the frontier</h2><p id="load-status">Connecting to frontier services…</p><button id="cancel-connect">BACK TO CREATE / JOIN</button></div><section id="hud" hidden><header><div><span class="eyebrow">WORLDS AWAKENED</span><br><strong id="room-label"></strong></div><div class="roomtools"><button id="copy">COPY CODE</button><button id="leave">LEAVE</button></div></header><div id="roster"></div><div id="status" role="status" aria-live="polite"></div><div id="help">Walk: WASD / touch · Look: drag / mouse · Inspect: E · Evidence: Tab</div><div id="crosshair">＋</div><div id="caption" aria-live="polite"></div><div id="actions"><button id="inspect">INSPECT</button><button id="archive">EVIDENCE</button><button id="ping">PING</button><button id="ready">READY TO BEGIN</button><button id="settings-play">SETTINGS</button></div><div id="joystick"><i></i></div></section><aside id="panel" hidden aria-label="Evidence and machine controls"><button id="close-panel" class="close">CLOSE ×</button><div id="panel-content"></div></aside><section id="settings" hidden><h2>Settings & accessibility</h2><label>Look sensitivity<input id="sensitivity" type="range" min="0.001" max="0.006" step="0.0005" value="0.003"></label><label><input type="checkbox" id="reduce" checked> Reduced camera motion</label><p>All mechanism clues have text and movement diagrams. No audio or color distinction is required.</p><button id="shelter">RETURN TO SHELTER</button><button id="settings-close">CLOSE</button><small>Development build: final licensed audio and artwork are not included yet.</small></section><div id="toast" role="alert"></div>`;
const $=(id:string)=>document.getElementById(id)!;const show=(id:string,on:boolean)=>{$(id).hidden=!on;};const escape=(t:string)=>t.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));let state:State|null=null,id='',token='',code='',socket:WebSocket|null=null,connected=false,manual=false,retries=0,response='',pattern='',panelId='',sensitivity=.003;
function toast(s:string){$('toast').textContent=s;show('toast',true);setTimeout(()=>show('toast',false),5000);}
function send(a:any){if(socket?.readyState===1)socket.send(JSON.stringify(a));else toast('Connection unavailable. Reconnecting…');}function act(a:any){if(state)send({...a,run:state.run,revision:state.revision,idempotency:crypto.randomUUID()});}
function save(){try{sessionStorage.setItem('wa-session',JSON.stringify({id,token,code}));}catch{toast('Storage is unavailable; refresh continuity may be limited.');}}
let connectionGeneration=0,retryTimer:ReturnType<typeof setTimeout>|undefined,attemptTimer:ReturnType<typeof setTimeout>|undefined,connectingSince=0,placeOnSnapshot=false,lastMessage=0;
function clearConnectionTimers(){clearTimeout(retryTimer);clearTimeout(attemptTimer);}
function returnToStart(message:string,keepIdentity=false){manual=true;connected=false;connectionGeneration++;clearConnectionTimers();socket?.close();socket=null;state=null;panelId='';response='';pattern='';show('loading',false);show('hud',false);show('panel',false);show('settings',false);show('title',true);$('veil').classList.remove('playing');$('session-message').textContent=message;show('resume',keepIdentity&&!!token);if(!keepIdentity){token='';id='';code='';try{sessionStorage.removeItem('wa-session');}catch{}}camera.position.set(31,13,43);camera.lookAt(0,9,-20);}
function connect(create=false,retry=false){if(!retry){clearConnectionTimers();connectingSince=Date.now();retries=0;}manual=false;connected=false;const generation=++connectionGeneration;socket?.close();show('title',false);show('loading',true);$('load-status').textContent=retries?'Reconnecting to frontier services… Your room can resume if the server is still running.':'Connecting to frontier services…';const ws=socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`);
const current=()=>generation===connectionGeneration;
const scheduleRetry=()=>{if(!current()||manual)return;connected=false;clearTimeout(attemptTimer);if(Date.now()-connectingSince>=120000){returnToStart('Frontier services are unavailable. Please try again. Your saved identity can resume if the room still exists.',!!token);return;}show('loading',true);$('load-status').textContent='Connection interrupted. Reconnecting to frontier services…';retryTimer=setTimeout(()=>connect(create&&!token,true),Math.min(1000*2**Math.min(retries++,4),10000)+Math.random()*300);};
attemptTimer=setTimeout(()=>{if(current()&&!connected)ws.close();},20000);
ws.onopen=()=>{if(!current())return;ws.send(JSON.stringify({type:'hello',create,code,token:token||undefined,name:($('name')as HTMLInputElement).value}));};
ws.onmessage=e=>{if(!current())return;lastMessage=Date.now();const a=JSON.parse(e.data);if(a.type==='welcome'){clearConnectionTimers();id=a.id;token=a.token;code=a.code;connected=true;retries=0;connectingSince=Date.now();placeOnSnapshot=true;save();show('title',false);show('loading',false);show('hud',true);show('resume',false);$('session-message').textContent='';$('veil').classList.add('playing');}if(a.type==='state'){const old=state;state=a.state;offset=state!.serverTime-Date.now();if(placeOnSnapshot){const self=state!.players.find(p=>p.id===id);if(self){camera.position.set(self.x,1.7,self.z);yaw=self.yaw||0;pitch=0;}placeOnSnapshot=false;}if(old&&old.run!==state!.run){camera.position.set(0,1.7,18);show('panel',false);panelId='';response='';pattern='';hint=0;toast('New diagnostic run. Evidence and machinery reset.');}updateUI();}if(a.type==='error'){if(a.code==='ROOM_GONE'){returnToStart('This temporary session has ended. The server may have restarted or the room expired. Create a new room and invite your group.');return;}if(a.code==='IDENTITY_GONE'||!connected){returnToStart(a.message);return;}toast(a.message);if(panelId&&!$('panel').hidden)renderPanel();}if(a.type==='response'){response=a.label;pattern=a.pattern;if(panelId&&!$('panel').hidden)renderPanel();}};
ws.onclose=e=>{if(!current()||manual)return;if(e.code===1008||e.reason==='Reconnected elsewhere'){returnToStart(e.reason==='Reconnected elsewhere'?'This player continued in another tab. You can create or join a room here.':'This temporary session has ended. Create a new room and invite your group.');return;}if(connected)connectingSince=Date.now();scheduleRetry();};ws.onerror=()=>{if(current())$('load-status').textContent='Waiting for frontier services… A free host may need time to wake up.';};}
setInterval(()=>{if(connected&&socket?.readyState===1){if(Date.now()-lastMessage>25000){socket.close();return;}send({type:'heartbeat'});}},10000);
$('resume').onclick=()=>connect();$('cancel-connect').onclick=()=>returnToStart('Connection cancelled. You can try again or create/join a room.',!!token);
$('create').onclick=()=>{token='';code='';connect(true);};$('join').onclick=()=>{token='';code=($('code')as HTMLInputElement).value.trim().toUpperCase();if(!code)return toast('Enter the room code.');connect();};$('leave').onclick=()=>returnToStart('You left the room. Other connected players can continue.');$('copy').onclick=()=>{navigator.clipboard?.writeText(code).then(()=>toast('Room code copied: '+code)).catch(()=>toast('Room code: '+code));};$('ready').onclick=()=>act({type:'ready'});$('archive').onclick=()=>{panelId='archive';renderPanel();};$('close-panel').onclick=()=>{show('panel',false);panelId='';};$('ping').onclick=()=>{panelId='communication';renderPanel();};$('settings-open').onclick=$('settings-play').onclick=()=>show('settings',true);$('settings-close').onclick=()=>show('settings',false);$('sensitivity').oninput=()=>sensitivity=Number(($('sensitivity')as HTMLInputElement).value);$('shelter').onclick=()=>{camera.position.set(0,1.7,18);show('settings',false);};
const points:Record<string,{x:number;z:number;label:string}>={log:{x:-10,z:1,label:'Maintenance record'},plate:{x:-12,z:3,label:'Human interface'},diagram:{x:8,z:-7,label:'Commissioning diagram'},response:{x:13,z:-9,label:'Ancient regulator'},secret:{x:22,z:12,label:'Weathered observation sketch'}};
function nearest(){let best='',dist=4;for(const[k,p]of Object.entries(points)){const d=Math.hypot(camera.position.x-p.x,camera.position.z-p.z);if(d<dist){best=k;dist=d;}}return best;}
function inspect(){const n=nearest();if(!n)return toast('Move closer to a record or mechanism.');panelId=n;response='';pattern='';act({type:'discover',id:n});if(n==='response'||n==='secret')send({type:'read',id:n});renderPanel();}
$('inspect').onclick=inspect;
function renderPanel(){if(!state)return;show('panel',true);let html='';if(panelId==='archive'){html='<div class="eyebrow">SHARED OBSERVATIONS</div><h2>Evidence archive</h2><p>Records are claims. Observations are evidence. Test your interpretation.</p>'+Object.entries(state.discoveries).map(([k,v])=>`<button data-evidence="${k}">${points[k]?.label||k}<small>Discovered by ${escape(v.by)}</small></button>`).join('')+(!Object.keys(state.discoveries).length?'<p>No discoveries yet. Explore the human shed and ancient passage.</p>':'')+'<h3>Team activity</h3>'+state.log.map(l=>`<p class="log">${escape(l.name)} — ${escape(l.text)}</p>`).join('');}
if(panelId==='communication')html='<div class="eyebrow">TEAM COMMUNICATION</div><h2>Share a status</h2><p>Messages appear in your team archive with your current location.</p>'+['Inspect this','Compare this','Ready','Stable','Try again'].map(t=>`<button data-status="${t}">${t.toUpperCase()}</button>`).join('');
if(panelId==='log')html='<div class="eyebrow">TECHNICIAN RECORD / CLAIM</div><h2>Replacement commissioned</h2><p>The landing feed operated before the coupling was replaced. Human power remains available; the ancient regulator has isolated the service line.</p><p>Check the installed mode against the regulator response. Isolate the feed before reconfiguration. One operator runs a test; another observes the regulator. Confirm stable behavior before restoring the landing.</p>';
if(panelId==='diagram')html='<div class="eyebrow">HUMAN WORK DIAGRAM / RECORD</div><h2>Read the machine</h2><div class="mode"><b>━ Steady feed</b><p>Continuous extension: provide continuous low service input.</p></div><div class="mode"><b>↔ Alternating feed</b><p>Balanced back-and-forth motion: alternate input between opposed elements.</p></div><div class="mode"><b>▯ ▯ ▯ Staged feed</b><p>Three successive sections settle: commission each section in order.</p></div><p>An interrupted response means the selected behavior is incompatible. This is a safe test, not a failure.</p>';
if(panelId==='plate')html=`<div class="eyebrow">HUMAN INTERFACE / OBSERVATION</div><h2>Service coupling</h2><p>Installed mode: <b>${state.mode}</b><br>Feed: <b>${state.isolated?'isolated for commissioning':'connected'}</b></p><button data-action="isolate">ISOLATE SERVICE FEED</button><div class="row">${['steady','alternating','staged'].map(m=>`<button data-mode="${m}">${m.toUpperCase()}</button>`).join('')}</div><button data-action="test">BEGIN / RENEW DIAGNOSTIC</button><p>Ask a different player at the ancient regulator to observe and confirm.</p><button data-action="activate" class="primary">RESTORE LANDING SERVICE</button><p class="small">Restoration starts the machinery. Run a safe test first.</p><button id="hint">OPTIONAL HELP</button><div id="hint-text"></div>`;
if(panelId==='response')html=`<div class="eyebrow">DIRECT MACHINE OBSERVATION</div><h2>Ancient regulator</h2><p>${state.test?'Diagnostic response: '+escape(response||'Inspect again to read the motion.'):'Awaiting a diagnostic feed from the human interface.'}</p><p>${state.test?(state.test.stable?'Sections settle without interruption.':'Motion breaks before settling. Compare the work diagram.'):'An operator at the human shed can begin the test.'}</p><button id="read-again">OBSERVE RESPONSE</button><button data-action="confirm">REPORT STABLE RESPONSE</button><button data-report="motion">SHARE OBSERVED MOTION</button>`;
if(panelId==='secret')html=`<div class="eyebrow">OBSERVATION SKETCH</div><h2>Beyond the service map</h2><p>A weathered sketch aligns a distant rock spur with the local regulator. The service drawing calls this installation isolated.</p><p>${state.discoveries.secret?'A matching response appears beyond the mapped service installation. What else is connected?':'Inspect this seam during a diagnostic test. A tiny movement may be more useful than a name.'}</p>`;
$('panel-content').innerHTML=html;document.querySelectorAll<HTMLButtonElement>('[data-status]').forEach(b=>b.onclick=()=>{act({type:'ping',text:b.dataset.status});show('panel',false);panelId='';});document.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(b=>b.onclick=()=>act({type:b.dataset.action}));document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>b.onclick=()=>act({type:'mode',mode:b.dataset.mode}));document.querySelectorAll<HTMLButtonElement>('[data-evidence]').forEach(b=>b.onclick=()=>{panelId=b.dataset.evidence!;renderPanel();});document.querySelectorAll<HTMLButtonElement>('[data-report]').forEach(b=>b.onclick=()=>{if(!pattern||!state?.test)return toast('Observe a running diagnostic first.');act({type:'observation',pattern});});if($('read-again'))$('read-again').onclick=()=>send({type:'read',id:'response'});if($('hint'))$('hint').onclick=()=>{hint++;$('hint-text').textContent=hint===1?'Compare the maintenance record with the commissioning diagram.':hint===2?'The regulator motion tells you what input it needs. Ask your observer to describe it.':`Observed requirement: ${pattern||'Ask a teammate to inspect the regulator; its motion identifies the mode.'} Isolate, select the matching mode, test, have your teammate confirm, then restore.`;};}
let hint=0,offset=0,uiSignature='';
function updateUI(){if(!state)return;$('room-label').textContent='ROOM '+state.code;$('roster').textContent=state.players.filter(p=>p.connected).map(p=>p.name+(p.id===id?' (you)':'')).join(' · ');$('status').textContent=state.phase==='waiting'?'Invite a second person. Both players select Ready to begin.':state.phase==='restored'?'Landing service restored. The supply launch has arrived.':state.phase==='activating'?'Restoration accepted. Watch the structure.':state.confirmation?'Stable response confirmed. Return to the interface to restore service.':'The beacon is offline. Explore, share observations and investigate together.';show('ready',state.phase==='waiting');if(state.phase==='restored'){$('ready').textContent=state.votes.includes(id)?'WAITING FOR TEAM':'REPLAY WITH TEAM';show('ready',true);$('ready').onclick=()=>act({type:'replay'});}else{$('ready').textContent='READY TO BEGIN';$('ready').onclick=()=>act({type:'ready'});}const signature=JSON.stringify([state.run,state.revision,state.discoveries,state.test,state.phase,state.log]);if(panelId&&!$('panel').hidden&&signature!==uiSignature)renderPanel();uiSignature=signature;syncAvatars();}
// Original geometry: atmosphere and composition, not a final asset-quality claim.
const canvas=$('world')as HTMLCanvasElement,renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;const scene=new THREE.Scene();scene.background=new THREE.Color('#899ca3');scene.fog=new THREE.FogExp2('#a0acb0',.008);const camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.1,700);camera.position.set(31,13,43);camera.lookAt(0,9,-20);scene.add(new THREE.HemisphereLight('#e5eaf1','#343b29',2));const sun=new THREE.DirectionalLight('#ffe0b1',3);sun.position.set(-45,65,30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-70,right:70,top:70,bottom:-70});scene.add(sun);
const stone=new THREE.MeshStandardMaterial({color:'#626d69',roughness:.94}),metal=new THREE.MeshStandardMaterial({color:'#52636b',roughness:.64,metalness:.5}),wood=new THREE.MeshStandardMaterial({color:'#74644f',roughness:.95}),grass=new THREE.MeshStandardMaterial({color:'#56634c',roughness:1});
function box(w:number,h:number,d:number,x:number,y:number,z:number,mat:THREE.Material){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);return m;}
box(160,1,160,0,-.55,0,grass);box(16,.15,120,-39,-.05,0,new THREE.MeshStandardMaterial({color:'#728e91',metalness:.45,roughness:.24}));for(let i=0;i<32;i++){const x=-80+(i*29)%160,z=-40-(i*17)%85;const m=new THREE.Mesh(new THREE.SphereGeometry(16+(i%3)*8,24,16),stone);m.scale.set(1,1.4,.8);m.position.set(x,7,z);scene.add(m);}for(let i=0;i<45;i++){const x=-70+(i*37)%140,z=-32-(i*23)%70;if(Math.abs(x)<16)continue;const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.25,.5,13,8),wood);trunk.position.set(x,5,z);scene.add(trunk);const crown=new THREE.Mesh(new THREE.SphereGeometry(4+i%3,16,12),new THREE.MeshStandardMaterial({color:i%2?'#394d40':'#465943',roughness:1}));crown.scale.y=1.5;crown.position.set(x,12,z);scene.add(crown);}
for(const x of[-16,16]){box(7,68,10,x,33,-36,stone);box(11,3,12,x,64,-36,stone);}box(39,7,10,0,54,-36,stone);box(28,3,8,0,19,-36,stone);for(let i=0;i<7;i++)box(1.2,55,1,16+Math.sin(i)*.5,28,-30+i*.35,new THREE.MeshStandardMaterial({color:'#919b91',roughness:.8}));
// Open sheds remain walkable; no jump/precision obstacles.
for(const x of[-16,-7]){box(.25,5,8,x,2.5,0,wood);}box(9.5,.3,9,-11.5,5.1,0,metal);box(9,.2,8,-11.5,.05,0,wood);box(2,1.5,1,-12,.85,3,metal);box(1,.08,.65,-10,1.25,1,new THREE.MeshStandardMaterial({color:'#d5ceaf',roughness:.9}));box(2,1.3,.4,8,.7,-7,wood);
const mechanism=new THREE.Group();mechanism.position.set(13,0,-9);scene.add(mechanism);const segments:THREE.Mesh[]=[];for(let i=0;i<3;i++){const m=new THREE.Mesh(new THREE.CylinderGeometry(1.1,1.2,1.5,32),metal);m.position.y=1+i*1.6;mechanism.add(m);segments.push(m);}box(4,.3,4,13,.15,-9,stone);const glowmat=new THREE.MeshStandardMaterial({color:'#b8d8d4',emissive:'#79beba',emissiveIntensity:0,roughness:.5});const glow=box(.3,52,.3,15,27,-30,glowmat);const beaconmat=new THREE.MeshStandardMaterial({color:'#cdb979',emissive:'#e6c979',emissiveIntensity:0});box(.4,6,.4,-23,3,12,metal);box(1.2,.6,1.2,-23,6.3,12,beaconmat);const boat=box(3,1,6,-39,.8,-60,metal);box(6,.25,10,-25,.1,15,wood);
for(const p of Object.values(points)){const marker=new THREE.Mesh(new THREE.CylinderGeometry(.2,.2,1.2,16),new THREE.MeshStandardMaterial({color:'#d1b67f',roughness:.7}));marker.position.set(p.x,.6,p.z);scene.add(marker);}
const avatars=new Map<string,THREE.Group>();function syncAvatars(){if(!state)return;for(const p of state.players){if(p.id===id||!p.connected)continue;let a=avatars.get(p.id);if(!a){a=new THREE.Group();a.add(new THREE.Mesh(new THREE.CapsuleGeometry(.3,.9,8,16),new THREE.MeshStandardMaterial({color:'#657982',roughness:.9})));const head=new THREE.Mesh(new THREE.SphereGeometry(.23,16,12),new THREE.MeshStandardMaterial({color:'#bda187',roughness:.9}));head.position.y=.85;a.add(head);a.position.y=.9;avatars.set(p.id,a);scene.add(a);}a.userData.target=new THREE.Vector3(p.x,.9,p.z);}for(const[k,a]of avatars)if(!state.players.some(p=>p.id===k&&p.connected)){scene.remove(a);avatars.delete(k);}}
const keys=new Set<string>();let yaw=0,pitch=0,drag=false,lastX=0,lastY=0,joyX=0,joyY=0;
window.addEventListener('keydown',e=>{if((e.target as HTMLElement).matches('input,textarea'))return;if(e.code==='Tab'&&state){e.preventDefault();panelId='archive';renderPanel();}if(e.code==='KeyE'&&state)inspect();if(e.code==='Escape'){panelId='';show('panel',false);show('settings',false);keys.clear();}keys.add(e.code);});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();joyX=joyY=0;});canvas.addEventListener('pointerdown',e=>{if(!state)return;drag=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag||!state)return;yaw-=(e.clientX-lastX)*sensitivity;pitch=Math.max(-1.2,Math.min(1.2,pitch-(e.clientY-lastY)*sensitivity));lastX=e.clientX;lastY=e.clientY;});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('pointercancel',()=>drag=false);const joy=$('joystick');joy.onpointerdown=e=>{joy.setPointerCapture(e.pointerId);moveJoy(e);};function moveJoy(e:PointerEvent){const r=joy.getBoundingClientRect();joyX=Math.max(-1,Math.min(1,(e.clientX-r.left-r.width/2)/40));joyY=Math.max(-1,Math.min(1,(e.clientY-r.top-r.height/2)/40));}joy.onpointermove=e=>{if(joy.hasPointerCapture(e.pointerId))moveJoy(e);};joy.onpointerup=joy.onpointercancel=()=>joyX=joyY=0;
window.addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();keys.clear();joyX=joyY=0;});let last=performance.now(),lastSend=0;
function frame(now:number){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;if(state){camera.rotation.set(pitch,yaw,0,'YXZ');if(connected&&$('panel').hidden&&$('settings').hidden){const f=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0)-joyY,s=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+joyX;const mag=Math.max(1,Math.hypot(f,s));camera.position.x+=(-Math.sin(yaw)*f+Math.cos(yaw)*s)*dt*5/mag;camera.position.z+=(-Math.cos(yaw)*f-Math.sin(yaw)*s)*dt*5/mag;camera.position.x=THREE.MathUtils.clamp(camera.position.x,-27,27);camera.position.z=THREE.MathUtils.clamp(camera.position.z,-19,24);}if(now-lastSend>70&&connected){send({type:'move',x:camera.position.x,z:camera.position.z,yaw});lastSend=now;}const n=nearest();$('inspect').textContent=n?'INSPECT '+points[n].label.toUpperCase():'INSPECT';const t=state.activationAt?(Date.now()+offset-state.activationAt)/1000:-1;const power=t>3?Math.min(1,(t-3)/6):0;glowmat.emissiveIntensity=power*3;beaconmat.emissiveIntensity=t>10?2:0;boat.position.z=t>12?Math.min(15,-60+(t-12)*7):-60;const active=!!state.test||t>3;segments.forEach((m,i)=>{m.rotation.y=active?Math.sin(now/800+i)*.3:0;m.position.y=1+i*1.6+(active?.12*Math.sin(now/600+i):0);});$('caption').textContent=t>=0&&t<3?'[The machinery becomes still.]':t>=3&&t<10?'[Deep machinery responds. Light travels into the structure.]':t>=10&&t<18?'[The landing beacon returns. A supply service approaches.]':t>=18?'[A distant structure answers with a matching response.]':'';for(const a of avatars.values())if(a.userData.target)a.position.lerp(a.userData.target,.2);}renderer.render(scene,camera);}requestAnimationFrame(frame);
try{const saved=JSON.parse(sessionStorage.getItem('wa-session')||'null');if(saved){id=saved.id;token=saved.token;code=saved.code;connect();}}catch{}
